### ISSUE TITLE
Merge this repo into KyleAMathews/typefaces

### ISSUE THREAD

**Issue by mirshko** [ajmalafif/typeface-inter#1]
hey there! 

Lovely finding this repo! was just what i was looking for! 

It would be awesome to merge this in with the https://github.com/KyleAMathews/typefaces repo that holds a ton of other open source fonts!

**Comment by ajmalafif** [comment]
Hi @mirshko, this actually has been requested quite a long time ago https://github.com/KyleAMathews/typefaces/issues/31

It was quite a long wait so I took some initiative to host it myself for now.

**Comment by mirshko** [comment]
ahh i see. i didn't realize the delay was due to the font being on fontsquirrel.

thank you for hosting this! 👍
