### ISSUE TITLE
Inter Web css file deleted

### ISSUE THREAD

**Issue by jshah4517** [ajmalafif/typeface-inter#7]
Hi there,

Thanks for maintaining this repository.

I noticed in the 3.17 commit, the `Inter Web/inter.css` file was deleted. Was this intentional?
https://github.com/ajmalafif/typeface-inter/commit/d8005e4eed3b510d9bf5000e68ae9f71d99037fd

It still exists in the Hinted for Windows folder - https://github.com/ajmalafif/typeface-inter/blob/main/Inter%20Hinted%20for%20Windows/Web/inter.css

We were using it. I can switch to the file in the parent directory, but that doesn't seem to have version numbers so it wouldn't update when there is a new release?

**Comment by ajmalafif** [comment]
hey there, 

ah it was intentional but I always thought I never included them before. Will including the `inter.css` file helps? I can quickly do that.

**Comment by jshah4517** [comment]
Might be safest to re-include it in terms of other people using it, but also updating with the main `inter.css` to include the version number too could also make sense.

**Comment by ajmalafif** [comment]
@jshah4517 hm I might need help with that. You mind doing a PR for this?

**Comment by jshah4517** [comment]
Done! I think no problem keeping that file deleted if you didn't intend for it to be there in the first place.

**Comment by ajmalafif** [comment]
thank you! @jshah4517 added the `inter.css` file

**Comment by jshah4517** [comment]
Thanks @ajmalafif
